#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Athena_PlayerCameraMode_SportValetADS

#include "Basic.hpp"

#include "Athena_PlayerCameraModeRangedTargeting_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Athena_PlayerCameraMode_SportValetADS.Athena_PlayerCameraMode_SportValetADS_C
// 0x0000 (0x0DD0 - 0x0DD0)
class UAthena_PlayerCameraMode_SportValetADS_C final : public UAthena_PlayerCameraModeRangedTargeting_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Athena_PlayerCameraMode_SportValetADS_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Athena_PlayerCameraMode_SportValetADS_C")
	}
	static class UAthena_PlayerCameraMode_SportValetADS_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthena_PlayerCameraMode_SportValetADS_C>();
	}
};
DUMPER7_ASSERTS_UAthena_PlayerCameraMode_SportValetADS_C;

SDK_NAMESPACE_END
