#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaChallengeRewards

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass AthenaChallengeRewards.AthenaChallengeRewards_C
// 0x0000 (0x02A0 - 0x02A0)
class UAthenaChallengeRewards_C final : public UAthenaChallengeRewards
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AthenaChallengeRewards_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AthenaChallengeRewards_C")
	}
	static class UAthenaChallengeRewards_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaChallengeRewards_C>();
	}
};
DUMPER7_ASSERTS_UAthenaChallengeRewards_C;

SDK_NAMESPACE_END
