#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassCurrencyPanel

#include "Basic.hpp"

#include "BattlePassBase_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BattlePassCurrencyPanel.BattlePassCurrencyPanel_C
// 0x0010 (0x02B0 - 0x02A0)
class UBattlePassCurrencyPanel_C final : public UFortBattlePassCurrencyPanel
{
public:
	class UImage*                                 BattleStarIcon;                                    // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 CustomSkinIcon;                                    // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattlePassCurrencyPanel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattlePassCurrencyPanel_C")
	}
	static class UBattlePassCurrencyPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassCurrencyPanel_C>();
	}
};
DUMPER7_ASSERTS_UBattlePassCurrencyPanel_C;

SDK_NAMESPACE_END
