#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassAlienTrooperPage

#include "Basic.hpp"

#include "BattlePassAlienTrooperPage_classes.hpp"
#include "BattlePassAlienTrooperPage_parameters.hpp"


SDK_NAMESPACE_START

// Function BattlePassAlienTrooperPage.BattlePassAlienTrooperPage_C.ExecuteUbergraph_BattlePassAlienTrooperPage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBattlePassAlienTrooperPage_C::ExecuteUbergraph_BattlePassAlienTrooperPage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassAlienTrooperPage_C", "ExecuteUbergraph_BattlePassAlienTrooperPage");

	Params::BattlePassAlienTrooperPage_C_ExecuteUbergraph_BattlePassAlienTrooperPage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BattlePassAlienTrooperPage.BattlePassAlienTrooperPage_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBattlePassAlienTrooperPage_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BattlePassAlienTrooperPage_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
