#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BattlePassAlienTrooperPage

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BattlePassS17UI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BattlePassAlienTrooperPage.BattlePassAlienTrooperPage_C
// 0x0010 (0x04D0 - 0x04C0)
class UBattlePassAlienTrooperPage_C final : public UFortBattlePassCustomSkinPageS17
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x04C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BattlePassAlienTrooperPage(int32 EntryPoint);
	void BP_OnActivated();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BattlePassAlienTrooperPage_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BattlePassAlienTrooperPage_C")
	}
	static class UBattlePassAlienTrooperPage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBattlePassAlienTrooperPage_C>();
	}
};
DUMPER7_ASSERTS_UBattlePassAlienTrooperPage_C;

SDK_NAMESPACE_END
