#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_F_Countdown

#include "Basic.hpp"

#include "BP_F_Countdown_classes.hpp"
#include "BP_F_Countdown_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_F_Countdown.BP_F_Countdown_C.ExecuteUbergraph_BP_F_Countdown
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::ExecuteUbergraph_BP_F_Countdown(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "ExecuteUbergraph_BP_F_Countdown");

	Params::BP_F_Countdown_C_ExecuteUbergraph_BP_F_Countdown Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Seconds Updated
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   SecondsRemaining_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::Seconds_Updated(int32 SecondsRemaining_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Seconds Updated");

	Params::BP_F_Countdown_C_Seconds_Updated Parms{};

	Parms.SecondsRemaining_0 = SecondsRemaining_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.CreateLocalizedCountdownText
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::CreateLocalizedCountdownText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "CreateLocalizedCountdownText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.BlinkTimer
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::BlinkTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "BlinkTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.ScrubComplete
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::ScrubComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "ScrubComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.FadeOut
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Fade                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ABP_F_Countdown_C::FadeOut(bool Fade)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "FadeOut");

	Params::BP_F_Countdown_C_FadeOut Parms{};

	Parms.Fade = Fade;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Stage2
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::Stage2()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Stage2");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Stage1
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::Stage1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Stage1");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_F_Countdown_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnComplete_CA92DED74DEB26F112504FA002394E57
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      UserWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::OnComplete_CA92DED74DEB26F112504FA002394E57(class UUserWidget* UserWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnComplete_CA92DED74DEB26F112504FA002394E57");

	Params::BP_F_Countdown_C_OnComplete_CA92DED74DEB26F112504FA002394E57 Parms{};

	Parms.UserWidget = UserWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnEventActive_A4FD7CB742A86161794F5D988537AF67
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::OnEventActive_A4FD7CB742A86161794F5D988537AF67(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnEventActive_A4FD7CB742A86161794F5D988537AF67");

	Params::BP_F_Countdown_C_OnEventActive_A4FD7CB742A86161794F5D988537AF67 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnEventUpdated_A4FD7CB742A86161794F5D988537AF67
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::OnEventUpdated_A4FD7CB742A86161794F5D988537AF67(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnEventUpdated_A4FD7CB742A86161794F5D988537AF67");

	Params::BP_F_Countdown_C_OnEventUpdated_A4FD7CB742A86161794F5D988537AF67 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnEventEnded_A4FD7CB742A86161794F5D988537AF67
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    EventName                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeUntilEnd                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FTimespan&                 TimeSinceBegin                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   TimespanRatio                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::OnEventEnded_A4FD7CB742A86161794F5D988537AF67(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnEventEnded_A4FD7CB742A86161794F5D988537AF67");

	Params::BP_F_Countdown_C_OnEventEnded_A4FD7CB742A86161794F5D988537AF67 Parms{};

	Parms.EventName = std::move(EventName);
	Parms.TimeUntilEnd = std::move(TimeUntilEnd);
	Parms.TimeSinceBegin = std::move(TimeSinceBegin);
	Parms.TimespanRatio = TimespanRatio;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnReady_711F6A5D45F01521379DF688123B4896
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::OnReady_711F6A5D45F01521379DF688123B4896()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnReady_711F6A5D45F01521379DF688123B4896");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OpacityMult__UpdateFunc
// (BlueprintEvent)

void ABP_F_Countdown_C::OpacityMult__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OpacityMult__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OpacityMult__FinishedFunc
// (BlueprintEvent)

void ABP_F_Countdown_C::OpacityMult__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OpacityMult__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_F_Countdown_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_F_Countdown_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnRep_Stage
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::OnRep_Stage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnRep_Stage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnRep_PlayAudio
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::OnRep_PlayAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnRep_PlayAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.Play Audio Internal
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   StartTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_F_Countdown_C::Play_Audio_Internal(float StartTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "Play Audio Internal");

	Params::BP_F_Countdown_C_Play_Audio_Internal Parms{};

	Parms.StartTime = StartTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_F_Countdown.BP_F_Countdown_C.StopAudioInternal
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::StopAudioInternal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "StopAudioInternal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_F_Countdown.BP_F_Countdown_C.OnRep_PlayLoopingAudio
// (BlueprintCallable, BlueprintEvent)

void ABP_F_Countdown_C::OnRep_PlayLoopingAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_F_Countdown_C", "OnRep_PlayLoopingAudio");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
