#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SpeedLines_Looping_Camera_Lens_Vehicle

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SpeedLines_Looping_Camera_Lens_Vehicle.BP_SpeedLines_Looping_Camera_Lens_Vehicle_C
// 0x0000 (0x02E0 - 0x02E0)
class ABP_SpeedLines_Looping_Camera_Lens_Vehicle_C final : public AEmitterCameraLensEffectBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SpeedLines_Looping_Camera_Lens_Vehicle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SpeedLines_Looping_Camera_Lens_Vehicle_C")
	}
	static class ABP_SpeedLines_Looping_Camera_Lens_Vehicle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SpeedLines_Looping_Camera_Lens_Vehicle_C>();
	}
};
DUMPER7_ASSERTS_ABP_SpeedLines_Looping_Camera_Lens_Vehicle_C;

SDK_NAMESPACE_END
