#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_Pedal

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CameraShake_Pedal.CameraShake_Pedal_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShake_Pedal_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_Pedal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_Pedal_C")
	}
	static class UCameraShake_Pedal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_Pedal_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_Pedal_C;

SDK_NAMESPACE_END
