#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CameraShake_HitImpact_Vehicle

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CameraShake_HitImpact_Vehicle.CameraShake_HitImpact_Vehicle_C
// 0x0000 (0x01B0 - 0x01B0)
class UCameraShake_HitImpact_Vehicle_C : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CameraShake_HitImpact_Vehicle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CameraShake_HitImpact_Vehicle_C")
	}
	static class UCameraShake_HitImpact_Vehicle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCameraShake_HitImpact_Vehicle_C>();
	}
};
DUMPER7_ASSERTS_UCameraShake_HitImpact_Vehicle_C;

SDK_NAMESPACE_END
