#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Couch_parent_Container_Athena_NoSearch

#include "Basic.hpp"

#include "Hotfix_BuildingPropWithLootComp_Parent_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Couch_parent_Container_Athena_NoSearch.Couch_parent_Container_Athena_NoSearch_C
// 0x0000 (0x0D40 - 0x0D40)
class ACouch_parent_Container_Athena_NoSearch_C final : public AHotfix_BuildingPropWithLootComp_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Couch_parent_Container_Athena_NoSearch_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Couch_parent_Container_Athena_NoSearch_C")
	}
	static class ACouch_parent_Container_Athena_NoSearch_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACouch_parent_Container_Athena_NoSearch_C>();
	}
};
DUMPER7_ASSERTS_ACouch_parent_Container_Athena_NoSearch_C;

SDK_NAMESPACE_END
