#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DagwoodCameraMode

#include "Basic.hpp"

#include "ValetRuntime_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DagwoodCameraMode.DagwoodCameraMode_C
// 0x0000 (0x0E20 - 0x0E20)
class UDagwoodCameraMode_C : public UFortCameraMode_Dagwood
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DagwoodCameraMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DagwoodCameraMode_C")
	}
	static class UDagwoodCameraMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDagwoodCameraMode_C>();
	}
};
DUMPER7_ASSERTS_UDagwoodCameraMode_C;

SDK_NAMESPACE_END
