#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DiscoveryGenericLobbyViolator

#include "Basic.hpp"

#include "DiscoveryGenericLobbyViolator_classes.hpp"
#include "DiscoveryGenericLobbyViolator_parameters.hpp"


SDK_NAMESPACE_START

// Function DiscoveryGenericLobbyViolator.DiscoveryGenericLobbyViolator_C.SetGamemodeName
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FText&                      SubText_0                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UDiscoveryGenericLobbyViolator_C::SetGamemodeName(const class FText& Name_0, const class FText& SubText_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DiscoveryGenericLobbyViolator_C", "SetGamemodeName");

	Params::DiscoveryGenericLobbyViolator_C_SetGamemodeName Parms{};

	Parms.Name_0 = std::move(Name_0);
	Parms.SubText_0 = std::move(SubText_0);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
