#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Galileo_Countdown

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Galileo_Countdown.Galileo_Countdown_C.ExecuteUbergraph_Galileo_Countdown
// 0x0020 (0x0020 - 0x0000)
struct Galileo_Countdown_C_ExecuteUbergraph_Galileo_Countdown final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_CustomEvent_NewText;                        // 0x0008(0x0018)()
};
DUMPER7_ASSERTS_Galileo_Countdown_C_ExecuteUbergraph_Galileo_Countdown;

// Function Galileo_Countdown.Galileo_Countdown_C.EventSetText
// 0x0018 (0x0018 - 0x0000)
struct Galileo_Countdown_C_EventSetText final
{
public:
	class FText                                   NewText;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_Galileo_Countdown_C_EventSetText;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
