#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_RollingEffects_Metal

#include "Basic.hpp"

#include "GCNL_RollingEffects_Parent_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCNL_RollingEffects_Metal.GCNL_RollingEffects_Metal_C
// 0x0000 (0x08D0 - 0x08D0)
class AGCNL_RollingEffects_Metal_C final : public AGCNL_RollingEffects_Parent_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCNL_RollingEffects_Metal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCNL_RollingEffects_Metal_C")
	}
	static class AGCNL_RollingEffects_Metal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_RollingEffects_Metal_C>();
	}
};
DUMPER7_ASSERTS_AGCNL_RollingEffects_Metal_C;

SDK_NAMESPACE_END
