#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Dagwood_Speedlines

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GCNL_Dagwood_Speedlines.GCNL_Dagwood_Speedlines_C
// 0x0000 (0x0808 - 0x0808)
class AGCNL_Dagwood_Speedlines_C final : public AFortGameplayCueNotify_Loop
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GCNL_Dagwood_Speedlines_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GCNL_Dagwood_Speedlines_C")
	}
	static class AGCNL_Dagwood_Speedlines_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCNL_Dagwood_Speedlines_C>();
	}
};
DUMPER7_ASSERTS_AGCNL_Dagwood_Speedlines_C;

SDK_NAMESPACE_END
