#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KiwiPlaylistRuntime

#include "Basic.hpp"

#include "KiwiPlaylistRuntime_classes.hpp"
#include "KiwiPlaylistRuntime_parameters.hpp"


SDK_NAMESPACE_START

// Function KiwiPlaylistRuntime.KiwiPawnComponent.HandlePawnEnterWaterBody
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PlayerPawn                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiPawnComponent::HandlePawnEnterWaterBody(class AFortPlayerPawn* PlayerPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiPawnComponent", "HandlePawnEnterWaterBody");

	Params::KiwiPawnComponent_HandlePawnEnterWaterBody Parms{};

	Parms.PlayerPawn = PlayerPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KiwiPlaylistRuntime.KiwiPawnComponent.HandlePawnExitWaterBody
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  PlayerPawn                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const bool                              bPawnIsOutsideOfAllWaterBodies                         (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiPawnComponent::HandlePawnExitWaterBody(class AFortPlayerPawn* PlayerPawn, const bool bPawnIsOutsideOfAllWaterBodies)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiPawnComponent", "HandlePawnExitWaterBody");

	Params::KiwiPawnComponent_HandlePawnExitWaterBody Parms{};

	Parms.PlayerPawn = PlayerPawn;
	Parms.bPawnIsOutsideOfAllWaterBodies = bPawnIsOutsideOfAllWaterBodies;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.BeginAsyncLoadOfItem
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class UFortItemDefinition*        ItemToLoad                                             (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::BeginAsyncLoadOfItem(const class UFortItemDefinition* ItemToLoad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "BeginAsyncLoadOfItem");

	Params::FortAthenaMutator_Kiwi_BeginAsyncLoadOfItem Parms{};

	Parms.ItemToLoad = ItemToLoad;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.HandleKiwiMannequinDestroyed
// (Final, Native, Private)
// Parameters:
// class AActor*                           MannequinActor                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::HandleKiwiMannequinDestroyed(class AActor* MannequinActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "HandleKiwiMannequinDestroyed");

	Params::FortAthenaMutator_Kiwi_HandleKiwiMannequinDestroyed Parms{};

	Parms.MannequinActor = MannequinActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.HandleKiwiNevadaVehicleDestroyed
// (Final, Native, Private)
// Parameters:
// class AActor*                           NevadaVehicleActor                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::HandleKiwiNevadaVehicleDestroyed(class AActor* NevadaVehicleActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "HandleKiwiNevadaVehicleDestroyed");

	Params::FortAthenaMutator_Kiwi_HandleKiwiNevadaVehicleDestroyed Parms{};

	Parms.NevadaVehicleActor = NevadaVehicleActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.HandlePlayerOnDisconnectedChanged
// (Final, Native, Private)
// Parameters:
// class AFortPlayerStateAthena*           PlayerState                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const bool                              bIsDisconnected                                        (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::HandlePlayerOnDisconnectedChanged(class AFortPlayerStateAthena* PlayerState, const bool bIsDisconnected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "HandlePlayerOnDisconnectedChanged");

	Params::FortAthenaMutator_Kiwi_HandlePlayerOnDisconnectedChanged Parms{};

	Parms.PlayerState = PlayerState;
	Parms.bIsDisconnected = bIsDisconnected;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.RegisterKiwiLocalVOManagerActor
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           InManager                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::RegisterKiwiLocalVOManagerActor(class AActor* InManager)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "RegisterKiwiLocalVOManagerActor");

	Params::FortAthenaMutator_Kiwi_RegisterKiwiLocalVOManagerActor Parms{};

	Parms.InManager = InManager;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.RegisterKiwiMannequin
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// class AFortPlayerMannequin*             Mannequin                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::RegisterKiwiMannequin(class AFortPlayerMannequin* Mannequin)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "RegisterKiwiMannequin");

	Params::FortAthenaMutator_Kiwi_RegisterKiwiMannequin Parms{};

	Parms.Mannequin = Mannequin;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.RegisterKiwiNevadaVehicle
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// class ASkeletalMeshActor*               NevadaVehicle                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::RegisterKiwiNevadaVehicle(class ASkeletalMeshActor* NevadaVehicle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "RegisterKiwiNevadaVehicle");

	Params::FortAthenaMutator_Kiwi_RegisterKiwiNevadaVehicle Parms{};

	Parms.NevadaVehicle = NevadaVehicle;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.RegisterPrisonAlienPatrolSequenceActor
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// class ALevelSequenceActor*              LevelSequenceActor                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::RegisterPrisonAlienPatrolSequenceActor(class ALevelSequenceActor* LevelSequenceActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "RegisterPrisonAlienPatrolSequenceActor");

	Params::FortAthenaMutator_Kiwi_RegisterPrisonAlienPatrolSequenceActor Parms{};

	Parms.LevelSequenceActor = LevelSequenceActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.SetActiveTimeOfDayManagerByTag
// (Final, BlueprintCosmetic, Native, Private, BlueprintCallable)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (ConstParm, Parm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::SetActiveTimeOfDayManagerByTag(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "SetActiveTimeOfDayManagerByTag");

	Params::FortAthenaMutator_Kiwi_SetActiveTimeOfDayManagerByTag Parms{};

	Parms.Tag = std::move(Tag);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.SetEnabledGameplayCueRecycling
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// const bool                              bEnable                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool AFortAthenaMutator_Kiwi::SetEnabledGameplayCueRecycling(const bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "SetEnabledGameplayCueRecycling");

	Params::FortAthenaMutator_Kiwi_SetEnabledGameplayCueRecycling Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.SetKiwiSequenceActor
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class ALevelSequenceActor*              SequenceActor                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_Kiwi::SetKiwiSequenceActor(class ALevelSequenceActor* SequenceActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "SetKiwiSequenceActor");

	Params::FortAthenaMutator_Kiwi_SetKiwiSequenceActor Parms{};

	Parms.SequenceActor = SequenceActor;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.GetKiwiLocalVOManagerActor
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class AActor*                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class AActor* AFortAthenaMutator_Kiwi::GetKiwiLocalVOManagerActor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "GetKiwiLocalVOManagerActor");

	Params::FortAthenaMutator_Kiwi_GetKiwiLocalVOManagerActor Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.GetKiwiSequenceActor
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class ALevelSequenceActor*              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class ALevelSequenceActor* AFortAthenaMutator_Kiwi::GetKiwiSequenceActor() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "GetKiwiSequenceActor");

	Params::FortAthenaMutator_Kiwi_GetKiwiSequenceActor Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.GetRegisteredKiwiMannequins
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<class AFortPlayerMannequin*>ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<class AFortPlayerMannequin*> AFortAthenaMutator_Kiwi::GetRegisteredKiwiMannequins() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "GetRegisteredKiwiMannequins");

	Params::FortAthenaMutator_Kiwi_GetRegisteredKiwiMannequins Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.GetRegisteredKiwiNevadaVehicles
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<class ASkeletalMeshActor*> ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<class ASkeletalMeshActor*> AFortAthenaMutator_Kiwi::GetRegisteredKiwiNevadaVehicles() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "GetRegisteredKiwiNevadaVehicles");

	Params::FortAthenaMutator_Kiwi_GetRegisteredKiwiNevadaVehicles Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_Kiwi.GetRegisteredPrisonAlienPatrolSequenceActors
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const TArray<class ALevelSequenceActor*>ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const TArray<class ALevelSequenceActor*> AFortAthenaMutator_Kiwi::GetRegisteredPrisonAlienPatrolSequenceActors() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_Kiwi", "GetRegisteredPrisonAlienPatrolSequenceActors");

	Params::FortAthenaMutator_Kiwi_GetRegisteredPrisonAlienPatrolSequenceActors Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.FortCheatManager_KiwiRelevancy.KiwiExplodePlayers
// (Final, BlueprintAuthorityOnly, Exec, Native, Public)

void UFortCheatManager_KiwiRelevancy::KiwiExplodePlayers()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortCheatManager_KiwiRelevancy", "KiwiExplodePlayers");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortCheatManager_KiwiRelevancy.KiwiStartKevinRoomZapping
// (Final, BlueprintAuthorityOnly, Exec, Native, Public)
// Parameters:
// const float                             ZapInterval                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UFortCheatManager_KiwiRelevancy::KiwiStartKevinRoomZapping(const float ZapInterval)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortCheatManager_KiwiRelevancy", "KiwiStartKevinRoomZapping");

	Params::FortCheatManager_KiwiRelevancy_KiwiStartKevinRoomZapping Parms{};

	Parms.ZapInterval = ZapInterval;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.ExplodeSquads
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)

void AFortAthenaMutator_KiwiRelevancy::ExplodeSquads()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "ExplodeSquads");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.KevinRoomStartZappingSquads
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ZapInterval                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_KiwiRelevancy::KevinRoomStartZappingSquads(float ZapInterval)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "KevinRoomStartZappingSquads");

	Params::FortAthenaMutator_KiwiRelevancy_KevinRoomStartZappingSquads Parms{};

	Parms.ZapInterval = ZapInterval;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.KevinRoomStopZappingSquads
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)

void AFortAthenaMutator_KiwiRelevancy::KevinRoomStopZappingSquads()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "KevinRoomStopZappingSquads");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.SetupOuterSpaceMannequins
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)

void AFortAthenaMutator_KiwiRelevancy::SetupOuterSpaceMannequins()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "SetupOuterSpaceMannequins");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.StartKevinRoomRelevancy
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)

void AFortAthenaMutator_KiwiRelevancy::StartKevinRoomRelevancy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "StartKevinRoomRelevancy");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.FortAthenaMutator_KiwiRelevancy.ZapSquads
// (Final, BlueprintAuthorityOnly, Native, Public, BlueprintCallable)
// Parameters:
// const int32                             FromIndex                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const int32                             ToIndex                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const int32                             MatchingOffset                                         (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AFortAthenaMutator_KiwiRelevancy::ZapSquads(const int32 FromIndex, const int32 ToIndex, const int32 MatchingOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("FortAthenaMutator_KiwiRelevancy", "ZapSquads");

	Params::FortAthenaMutator_KiwiRelevancy_ZapSquads Parms{};

	Parms.FromIndex = FromIndex;
	Parms.ToIndex = ToIndex;
	Parms.MatchingOffset = MatchingOffset;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.ClientSetEnableKevinCubeInteract
// (Net, NetReliable, Native, Event, Public, NetClient)
// Parameters:
// const class AKiwiKevinCubeInteractActor*KevinCubeInteractActor                                 (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bInteracting                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::ClientSetEnableKevinCubeInteract(const class AKiwiKevinCubeInteractActor* KevinCubeInteractActor, bool bInteracting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "ClientSetEnableKevinCubeInteract");

	Params::KiwiControllerComponent_ClientSetEnableKevinCubeInteract Parms{};

	Parms.KevinCubeInteractActor = KevinCubeInteractActor;
	Parms.bInteracting = bInteracting;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.ClientSetupSpaceMannequins
// (Net, NetReliable, Native, Event, Public, NetClient)
// Parameters:
// const TArray<class AFortPlayerPawn*>&   PlayerPawnsToLoadoutCopy                               (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::ClientSetupSpaceMannequins(const TArray<class AFortPlayerPawn*>& PlayerPawnsToLoadoutCopy)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "ClientSetupSpaceMannequins");

	Params::KiwiControllerComponent_ClientSetupSpaceMannequins Parms{};

	Parms.PlayerPawnsToLoadoutCopy = std::move(PlayerPawnsToLoadoutCopy);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.ClientZapPawns
// (Net, NetReliable, Native, Event, Public, NetClient)
// Parameters:
// const TArray<class AFortPlayerPawn*>&   PawnsToKill                                            (ConstParm, Parm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const struct FGameplayTag&              ZapReason                                              (ConstParm, Parm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::ClientZapPawns(const TArray<class AFortPlayerPawn*>& PawnsToKill, const struct FGameplayTag& ZapReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "ClientZapPawns");

	Params::KiwiControllerComponent_ClientZapPawns Parms{};

	Parms.PawnsToKill = std::move(PawnsToKill);
	Parms.ZapReason = std::move(ZapReason);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.OnMovementModeChanged
// (Final, Native, Private)
// Parameters:
// class ACharacter*                       Character                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// EMovementMode                           PreviousMovementMode                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// uint8                                   PreviousCustomMode                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::OnMovementModeChanged(class ACharacter* Character, EMovementMode PreviousMovementMode, uint8 PreviousCustomMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "OnMovementModeChanged");

	Params::KiwiControllerComponent_OnMovementModeChanged Parms{};

	Parms.Character = Character;
	Parms.PreviousMovementMode = PreviousMovementMode;
	Parms.PreviousCustomMode = PreviousCustomMode;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.OnPlayerPawnPossessed
// (Final, Native, Private)
// Parameters:
// class APawn*                            PossessedPawn                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::OnPlayerPawnPossessed(class APawn* PossessedPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "OnPlayerPawnPossessed");

	Params::KiwiControllerComponent_OnPlayerPawnPossessed Parms{};

	Parms.PossessedPawn = PossessedPawn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.OnSkyTubeChanged
// (Final, Native, Private)
// Parameters:
// class AFortPlayerPawn*                  Pawn                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortSkyTube*                     NewSkyTube                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AFortSkyTube*                     OldSkyTube                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::OnSkyTubeChanged(class AFortPlayerPawn* Pawn, class AFortSkyTube* NewSkyTube, class AFortSkyTube* OldSkyTube)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "OnSkyTubeChanged");

	Params::KiwiControllerComponent_OnSkyTubeChanged Parms{};

	Parms.Pawn = Pawn;
	Parms.NewSkyTube = NewSkyTube;
	Parms.OldSkyTube = OldSkyTube;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.PlayPawnZapEffects
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class AFortPlayerPawn*>&   PawnsToKill                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// const struct FGameplayTag&              ZapReason                                              (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::PlayPawnZapEffects(const TArray<class AFortPlayerPawn*>& PawnsToKill, const struct FGameplayTag& ZapReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "PlayPawnZapEffects");

	Params::KiwiControllerComponent_PlayPawnZapEffects Parms{};

	Parms.PawnsToKill = std::move(PawnsToKill);
	Parms.ZapReason = std::move(ZapReason);

	UObject::ProcessEvent(Func, &Parms);
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.PlayPrisonAlienPatrolSequence
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)

void UKiwiControllerComponent::PlayPrisonAlienPatrolSequence()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "PlayPrisonAlienPatrolSequence");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.RegisterLocalSpaceMannequin
// (Final, BlueprintCosmetic, Native, Public, BlueprintCallable)
// Parameters:
// class AFortPlayerMannequin*             SpacePlayerMannequin                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const int32                             MannequinIndex                                         (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::RegisterLocalSpaceMannequin(class AFortPlayerMannequin* SpacePlayerMannequin, const int32 MannequinIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "RegisterLocalSpaceMannequin");

	Params::KiwiControllerComponent_RegisterLocalSpaceMannequin Parms{};

	Parms.SpacePlayerMannequin = SpacePlayerMannequin;
	Parms.MannequinIndex = MannequinIndex;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.UpdateSpaceMannequinCosmeticLoadout
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class AFortPlayerMannequin*             Mannequin                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FFortAthenaLoadout&        Loadout                                                (ConstParm, Parm, NativeAccessSpecifierPublic)

void UKiwiControllerComponent::UpdateSpaceMannequinCosmeticLoadout(class AFortPlayerMannequin* Mannequin, const struct FFortAthenaLoadout& Loadout)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "UpdateSpaceMannequinCosmeticLoadout");

	Params::KiwiControllerComponent_UpdateSpaceMannequinCosmeticLoadout Parms{};

	Parms.Mannequin = Mannequin;
	Parms.Loadout = std::move(Loadout);

	UObject::ProcessEvent(Func, &Parms);
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.GetPrisonAlienPatrolSequenceActorForBlock
// (BlueprintCosmetic, Event, Protected, HasOutParams, BlueprintEvent, Const)
// Parameters:
// const struct FGameplayTag&              PrisonBlockTag                                         (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ALevelSequenceActor*              ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class ALevelSequenceActor* UKiwiControllerComponent::GetPrisonAlienPatrolSequenceActorForBlock(const struct FGameplayTag& PrisonBlockTag) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "GetPrisonAlienPatrolSequenceActorForBlock");

	Params::KiwiControllerComponent_GetPrisonAlienPatrolSequenceActorForBlock Parms{};

	Parms.PrisonBlockTag = std::move(PrisonBlockTag);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function KiwiPlaylistRuntime.KiwiControllerComponent.GetPrisonTeleportSquadStart
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const class AFortSquadStart*            ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const class AFortSquadStart* UKiwiControllerComponent::GetPrisonTeleportSquadStart() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiControllerComponent", "GetPrisonTeleportSquadStart");

	Params::KiwiControllerComponent_GetPrisonTeleportSquadStart Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
