#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KiwiRuntime

#include "Basic.hpp"

#include "KiwiRuntime_classes.hpp"
#include "KiwiRuntime_parameters.hpp"


SDK_NAMESPACE_START

// Function KiwiRuntime.KiwiTubeItems.BeginTubeFlow
// (Final, Native, Public, BlueprintCallable)

void AKiwiTubeItems::BeginTubeFlow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "BeginTubeFlow");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.OnPlayerHitItem
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class AFortPlayerPawn*                  Player                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FKiwiTubeItemDef&          HitItem                                                (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
// const struct FKiwiTubeItemType&         HitItemType                                            (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)

void AKiwiTubeItems::OnPlayerHitItem(class AFortPlayerPawn* Player, const struct FKiwiTubeItemDef& HitItem, const struct FKiwiTubeItemType& HitItemType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "OnPlayerHitItem");

	Params::KiwiTubeItems_OnPlayerHitItem Parms{};

	Parms.Player = Player;
	Parms.HitItem = std::move(HitItem);
	Parms.HitItemType = std::move(HitItemType);

	UObject::ProcessEvent(Func, &Parms);
}


// Function KiwiRuntime.KiwiTubeItems.OnTubeMeshComponentOverlap
// (Final, Native, Private, HasOutParams)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class AActor*                           OtherActor                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UPrimitiveComponent*              OtherComp                                              (Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   OtherBodyIndex                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bFromSweep                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FHitResult&                SweepResult                                            (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference, NativeAccessSpecifierPublic)

void AKiwiTubeItems::OnTubeMeshComponentOverlap(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "OnTubeMeshComponentOverlap");

	Params::KiwiTubeItems_OnTubeMeshComponentOverlap Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.SetFlowDirection
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const ETubeFlowDirection                NewFlowDirection                                       (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void AKiwiTubeItems::SetFlowDirection(const ETubeFlowDirection NewFlowDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "SetFlowDirection");

	Params::KiwiTubeItems_SetFlowDirection Parms{};

	Parms.NewFlowDirection = NewFlowDirection;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.StopTubeFlow
// (Final, Native, Public, BlueprintCallable)

void AKiwiTubeItems::StopTubeFlow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "StopTubeFlow");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.ToggleFlowDirection
// (Final, Native, Public, BlueprintCallable)

void AKiwiTubeItems::ToggleFlowDirection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "ToggleFlowDirection");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.UpdateCollisionOnItems
// (Final, Native, Protected, BlueprintCallable)

void AKiwiTubeItems::UpdateCollisionOnItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "UpdateCollisionOnItems");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.UpdateItemMovementAlongPath
// (Final, Native, Private)

void AKiwiTubeItems::UpdateItemMovementAlongPath()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "UpdateItemMovementAlongPath");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function KiwiRuntime.KiwiTubeItems.CanEnableCollisionOnItems
// (Native, Event, Protected, BlueprintEvent, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool AKiwiTubeItems::CanEnableCollisionOnItems() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KiwiTubeItems", "CanEnableCollisionOnItems");

	Params::KiwiTubeItems_CanEnableCollisionOnItems Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
