#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MediaMovieStreamer

#include "Basic.hpp"

#include "MediaMovieStreamer_classes.hpp"


SDK_NAMESPACE_START

// Function MediaMovieStreamer.MediaMovieAssets.OnMediaEnd
// (Final, Native, Private)

void UMediaMovieAssets::OnMediaEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MediaMovieAssets", "OnMediaEnd");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
