#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeltUI

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function MeltUI.MeltWidgetBase.CacheAndGetSeaLevel
// 0x0004 (0x0004 - 0x0000)
struct MeltWidgetBase_CacheAndGetSeaLevel final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeltWidgetBase_CacheAndGetSeaLevel;

// Function MeltUI.MeltWidgetBase.MutatorReady
// 0x0008 (0x0008 - 0x0000)
struct MeltWidgetBase_MutatorReady final
{
public:
	const class AFortAthenaMutator_Fill*          MutatorActor;                                      // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeltWidgetBase_MutatorReady;

// Function MeltUI.MeltWidgetBase.GetFillMutator
// 0x0008 (0x0008 - 0x0000)
struct MeltWidgetBase_GetFillMutator final
{
public:
	class AFortAthenaMutator_Fill*                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MeltWidgetBase_GetFillMutator;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
