#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MoreInfo_Ressources_MobileButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass MoreInfo_Ressources_MobileButton.MoreInfo_Ressources_MobileButton_C
// 0x0010 (0x0BE0 - 0x0BD0)
class UMoreInfo_Ressources_MobileButton_C final : public UCommonButtonBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Hover;                                             // 0x0BD8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnHovered();
	void BP_OnUnhovered();
	void ExecuteUbergraph_MoreInfo_Ressources_MobileButton(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MoreInfo_Ressources_MobileButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MoreInfo_Ressources_MobileButton_C")
	}
	static class UMoreInfo_Ressources_MobileButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMoreInfo_Ressources_MobileButton_C>();
	}
};
DUMPER7_ASSERTS_UMoreInfo_Ressources_MobileButton_C;

SDK_NAMESPACE_END
