#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPCConvertedIndicatorMarker

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass NPCConvertedIndicatorMarker.NPCConvertedIndicatorMarker_C
// 0x0008 (0x0520 - 0x0518)
class UNPCConvertedIndicatorMarker_C final : public UAthenaMarkedActorIndicator
{
public:
	class UImage*                                 IrwinIndicator;                                    // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NPCConvertedIndicatorMarker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NPCConvertedIndicatorMarker_C")
	}
	static class UNPCConvertedIndicatorMarker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNPCConvertedIndicatorMarker_C>();
	}
};
DUMPER7_ASSERTS_UNPCConvertedIndicatorMarker_C;

SDK_NAMESPACE_END
