#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerCraftingComponent

#include "Basic.hpp"

#include "CraftingRuntime_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PlayerCraftingComponent.PlayerCraftingComponent_C
// 0x0000 (0x04F8 - 0x04F8)
class UPlayerCraftingComponent_C final : public UCraftingObjectComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerCraftingComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerCraftingComponent_C")
	}
	static class UPlayerCraftingComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerCraftingComponent_C>();
	}
};
DUMPER7_ASSERTS_UPlayerCraftingComponent_C;

SDK_NAMESPACE_END
