#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuartzMusicTrackComponent_SpicySake

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "QuartzMusicTrackComponent_DataTracker_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass QuartzMusicTrackComponent_SpicySake.QuartzMusicTrackComponent_SpicySake_C
// 0x0018 (0x01E0 - 0x01C8)
class UQuartzMusicTrackComponent_SpicySake_C final : public UQuartzMusicTrackComponent_DataTracker_C
{
public:
	float                                         InterpFloat_Circling;                              // 0x01C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InterpFloat_Attacking;                             // 0x01CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           EventTag_Circling;                                 // 0x01D0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           EventTag_Attacking;                                // 0x01D8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void OnDataTrackerUpdate();
	float UpdateInterpValue(float InterpValue, const struct FGameplayTag& EventTag, float Attack_Speed, float Release_Speed);
	void HandleMixState();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuartzMusicTrackComponent_SpicySake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuartzMusicTrackComponent_SpicySake_C")
	}
	static class UQuartzMusicTrackComponent_SpicySake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuartzMusicTrackComponent_SpicySake_C>();
	}
};
DUMPER7_ASSERTS_UQuartzMusicTrackComponent_SpicySake_C;

SDK_NAMESPACE_END
