#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SoundLib_JumpBoots

#include "Basic.hpp"

#include "FoleyLib_Character_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SoundLib_JumpBoots.SoundLib_JumpBoots_C
// 0x0000 (0x00B0 - 0x00B0)
class USoundLib_JumpBoots_C final : public UFoleyLib_Character_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SoundLib_JumpBoots_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SoundLib_JumpBoots_C")
	}
	static class USoundLib_JumpBoots_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USoundLib_JumpBoots_C>();
	}
};
DUMPER7_ASSERTS_USoundLib_JumpBoots_C;

SDK_NAMESPACE_END
