#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TODM_Disabled

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "MASTER_TODM_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass TODM_Disabled.TODM_Disabled_C
// 0x0010 (0x1110 - 0x1100)
class ATODM_Disabled_C final : public AMASTER_TODM_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_TODM_Disabled_C;                    // 0x1100(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void UserConstructionScript();
	void DisableLightAndFog(bool Enable);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_TODM_Disabled(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TODM_Disabled_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TODM_Disabled_C")
	}
	static class ATODM_Disabled_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATODM_Disabled_C>();
	}
};
DUMPER7_ASSERTS_ATODM_Disabled_C;

SDK_NAMESPACE_END
