#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Valet_BigRig_CameraMode

#include "Basic.hpp"

#include "DagwoodCameraMode_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Valet_BigRig_CameraMode.Valet_BigRig_CameraMode_C
// 0x0000 (0x0E20 - 0x0E20)
class UValet_BigRig_CameraMode_C final : public UDagwoodCameraMode_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Valet_BigRig_CameraMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Valet_BigRig_CameraMode_C")
	}
	static class UValet_BigRig_CameraMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UValet_BigRig_CameraMode_C>();
	}
};
DUMPER7_ASSERTS_UValet_BigRig_CameraMode_C;

SDK_NAMESPACE_END
