#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ValetGameStateComponent

#include "Basic.hpp"

#include "ValetRuntime_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ValetGameStateComponent.ValetGameStateComponent_C
// 0x0000 (0x02C0 - 0x02C0)
class UValetGameStateComponent_C final : public UFortGameStateComponent_Valet
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ValetGameStateComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ValetGameStateComponent_C")
	}
	static class UValetGameStateComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UValetGameStateComponent_C>();
	}
};
DUMPER7_ASSERTS_UValetGameStateComponent_C;

SDK_NAMESPACE_END
