#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VkContentPackageResolver

#include "Basic.hpp"

#include "VkEngineTypes_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct VkContentPackageResolver.VkContentPackageRequest
// 0x0080 (0x0080 - 0x0000)
struct FVkContentPackageRequest final
{
public:
	class FString                                 ProjectID;                                         // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVkModuleVersionRef                    Root;                                              // 0x0010(0x0020)(NativeAccessSpecifierPublic)
	TMap<class FString, int32>                    Resolutions;                                       // 0x0030(0x0050)(NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FVkContentPackageRequest;

SDK_NAMESPACE_END
