#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKEditUI

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function VKEditUI.VKDebugMessagesBase.BP_OnGameStateInitialized
// 0x0008 (0x0008 - 0x0000)
struct VKDebugMessagesBase_BP_OnGameStateInitialized final
{
public:
	class AFortGameState*                         GameState;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VKDebugMessagesBase_BP_OnGameStateInitialized;

// Function VKEditUI.VKDebugMessagesBase.HandleGameStateInitialized
// 0x0008 (0x0008 - 0x0000)
struct VKDebugMessagesBase_HandleGameStateInitialized final
{
public:
	class AFortGameState*                         GameState;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VKDebugMessagesBase_HandleGameStateInitialized;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
