#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VKEditUI

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


SDK_NAMESPACE_START

// Class VKEditUI.VKDebugMessagesBase
// 0x0000 (0x02C8 - 0x02C8)
class UVKDebugMessagesBase final : public UFortHUDElementWidget
{
public:
	void BP_OnGameStateInitialized(class AFortGameState* GameState);
	void HandleGameStateInitialized(class AFortGameState* GameState);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("VKDebugMessagesBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"VKDebugMessagesBase")
	}
	static class UVKDebugMessagesBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVKDebugMessagesBase>();
	}
};
DUMPER7_ASSERTS_UVKDebugMessagesBase;

SDK_NAMESPACE_END
